---
- name: Check for Updates Without Applying on Debian-based Systems
  hosts: all
  tasks:
    - name: Check for available updates
      apt:
        list: upgrades
      register: available_updates

    - name: Display available updates
      debug:
        var: available_updates
