---
- name: Pull Code from GitHub, Execute a Command, and Delete the Cloned Repo
  hosts: all
  tasks:
    - name: Clone or update the GitHub repository
      git:
        repo: git@github.com:rexdivakar/semaphore_ansible.git
        dest: /tmp/ansible_build
        update: yes
        version: main
      register: git_output
      notify:
        - Execute Command
        - Delete Cloned Repo

    - name: Execute a Command
      shell: /home/zki2s1l/miniconda3/bin/python /tmp/ansible_build/scripts/test.py
      register: command_output

    - name: Display the output of the Python script execution
      debug:
        var: command_output.stdout
    
    - name: Notify Discord on Failure
      community.general.discord:
        webhook_id: your_webhook_id
        webhook_token: 'https://discord.com/api/webhooks/1170236764263284757/_cjqGUWTmT8G-TWFMH7MRcxuEwHBESdZjNkJ5bm6qQlOvAu1UQh4S0e6dhrOeKcsxc5D'
        content: "An error occurred while executing the Ansible playbook. Here's the error message:\n\n{{ command_output.stderr }}"
        when: command_output.failed

  handlers:
    - name: Delete Cloned Repo
      file:
        path: /tmp/ansible_build
        state: absent


