---
- name: Pull Code from GitHub, Execute a Command, and Notify Discord on Failure
  hosts: all
  tasks:
    - name: Clone or update the GitHub repository
      git:
        repo: https://github.com/rexdivakar/semaphore_ansible/
        dest: /tmp/ansible_build
        update: yes
        version: main
      register: git_output
      notify:
        - Execute Command
        - Delete Cloned Repo

    - name: Execute a Command
      shell: /home/zki2s1l/miniconda3/bin/python /tmp/ansible_build/scripts/test.py
      register: command_output
      failed_when: "'ERROR' in command_output.stderr"  # Detect an error in the script's stderr

    - name: Display the output of the Python script execution
      debug:
        var: command_output.stdout

  handlers:
    - name: Delete Cloned Repo
      file:
        path: /tmp/ansible_build
        state: absent

    - name: Notify Discord on Failure
      community.general.discord:
        webhook_id: 1
        webhook_token: https://discord.com/api/webhooks/1170236764263284757/_cjqGUWTmT8G-TWFMH7MRcxuEwHBESdZjNkJ5bm6qQlOvAu1UQh4S0e6dhrOeKcsxc5D
        content: "An error occurred while executing the Ansible playbook. Here's the error message:\n\n{{ command_output.stderr }}"
      when: command_output.failed

