- name: Fetch uptime status of servers
  hosts: all
  gather_facts: true

  tasks:
    - name: Get uptime status
      shell: uptime -p
      register: uptime_output

    - name: Display uptime result
      debug:
        var: uptime_output.stdout
